### PR TITLE
Improve README and code quality

### PR DESCRIPTION
**Pull request by MoaufmKlo**

### CODE REVIEW

**Comment by robloxianstudio123** [comment]
Thanks to you, for fixing the script, mine was bad
Version 2 is now out, Version 1 is still downloadable, but you should use the V.2

**Review by robloxianstudio123 — APPROVED** [review]

**Comment by robloxianstudio123** [comment]
> Thanks to you, for fixing the script, mine was bad
> Version 2 is now out, Version 1 is still downloadable, but you should use the V.2

Forgot one more thing: Where's the download?

**Comment by MoaufmKlo** [comment]
> Forgot one more thing: Where's the download?
You just copy the content of the file.

**Comment by robloxianstudio123** [comment]
I've released the version 2. 

> [NOTE ABOUT THIS PLUGIN]:
> If there any issues with this plugin, please go to issues section.
> If you want to improve the poor script, you can go to pull requests section

**Comment by robloxianstudio123** [comment]
> I've released the version 2.
> 
> > [NOTE ABOUT THIS PLUGIN]:
> > If there any issues with this plugin, please go to issues section.
> > If you want to improve the poor script, you can go to pull requests section

Wait, forgot to put the link: https://github.com/robloxianstudio123/RBXStudioCameraBypass/releases/tag/v2.0

**Comment by MoaufmKlo** [comment]
This was indirectly merged.

**Comment by robloxianstudio123** [comment]
took you 2 years to respond  to this???????

**Review by robloxianstudio123 — COMMENTED** [review]
perfection

**Pull request closed without merging**
